language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

  - npm run build
  - npm i serve
  - serve -s build -l 3000 &

script:
  - npm test -- --coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

deploy:
  api_key:
    secure: I6CxbHL8X908s5BWABWm9cSRZ03rgQgZ7Qm2JJmJH9TCST0ozM81Z+cKXG7uxa3KwKo9Z5E5c8nQ+NDrSKPeVkGcAn1hAQ0cuIQhq1rOBfFHpmwYmOhoHxBFQ817H3gd6HQtS9jcX9jXOQOD6KQ9V8I4w9Jh6oED4jXWc+HHR3Sd0DggEKtLO3OswLLZYNGGR7FIebBLKta5CLulkysxacw0sUnI7c7uXGfSw1yEdsPZsVSiB1VfWKlnP69khUm4FjbGnmxJK4Ak5nAQXXKf/2v53yKQnmlB1Xn0ttptY3gChRuzyjBmqm2gQE0o/SuO4wVEraGpG7Cg7CeMeZvHZIP3mnKTRozQtSAadgmJdjuCjI1hvRr4Ni41oF/DbwkpIlA2/sF+SaR3TbQXrlmSM74BRHpwA+o2wo1IoEHTY9lrkfiKfVAlzJT2p5s1X0M4d3rBjM2PhU4GZmNHU6ve/9+LlFcfUkLdGqrKW2+tqhe7plM5H3zTd9VeXuRydQT+WRkKbQ4JTDoujTQtyeM5rVmPEvuWRn63R9Hb+5uIqXWtNdMUpGCprSZ+auEwuqU9p4IJRXeZyltnRGi3aQv+YduusCiiiG82mPWKFanZ2sAfFeaVSLTEo8wW+rcSVleyLnMTWO5B2idnW5B7nvbq9iurGUl1lTHle73dkSS7Tcc=
